server:
  servlet:
    context-path: /api

aws:
  cognito:
    userPoolId: ap-northeast-2_YaKUHlVpc
    appClientId: 5gur124q0jk0rbddvikqcmdrka

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/snail-email  
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true