@startuml
entity "Users" as e01 {
  *user_id : integer <<generated>>
  --
  user_name : String
  user_email : String
  user_pw : String
  join_date : timestamp
  update_date : timestamp
  }

entity "Emails" as e02 {
  *email_id : integer <<generated>>
  --
  email_sennder_id : integer
  email_receiver_id : integer
  email_title : String 
  email_content : String
  create_date : timestamp
  send_date : timestamp
  send_yn : boolean
}

e01 }|-- e02
@enduml
